Feature/174 geolocate tracking
OnroerendErfgoed/oerelia pull request #175
Opened 2022-05-12 11:06 UTC by pegahmoh

fers #174

2022-05-12 11:21 UTC, cedrikv requested changes

2022-05-12 11:21 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +    const positionFeature = this._createFeature();
ga je hier niet heel veel features aanmaken in dezelfde laag? miss beter eens de laag leeg maken, of de bestaande feature aanpassen.

2022-05-12 11:21 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +    view.setZoom(zoomLevel);
hier ben ik niet zeker of we dit willen doen bij elke update, als de gebuiker ondertussen zelf zoomt of ergens anders heen pant, komt hij altijd terug op deze extent terecht, wat vervelend kan zijn. Dus indien mogelijk 1x zoomen & cetreren, nadien enkel nog de lat lon updaten.

2022-05-12 11:21 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +      [pos.coords.longitude, pos.coords.latitude],
Eventueel om te testen: bij de lat en lon een random getal tussen ? en ? bijtellen, zodat het punt beweegt?

2022-05-16 11:19 UTC, pegahmoh commented on src/gis-utils/components/ol-geolocate.ts
> +      [pos.coords.longitude, pos.coords.latitude],
Deze heb ik wat geprobeerd maar het zal de accuracy verminderen en het punt beweegt ook niet.

2022-05-17 08:12 UTC, cedrikv requested changes

2022-05-17 08:12 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +    console.debug('ol-geolocate::_zoomToLocation');
log lijn

2022-05-17 08:12 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +        console.debug(error);
beter een console.error dan?

2022-05-17 08:12 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +    console.debug('ol-geolocate::_addPositionFeature', pos.coords);
log lijn

2022-05-17 08:12 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +    positionFeature.setGeometry(coordinates ? new ol.geom.Point(coordinates) : null);
deze zal 2x uitgevoerd worden ils de if true is, nee? best die lijn gewoon uit de if halen?

2022-05-17 11:25 UTC, cedrikv requested changes
als ik 2x op de geolocate klik, verdwijnt de marker

2022-05-17 11:32 UTC, cedrikv commented on src/gis-utils/components/ol-geolocate.ts
> +      navigator.geolocation.watchPosition(function(pos) {
nog een type toekennen aan pos

2022-05-18 15:31 UTC, cedrikv approved these changes

2022-05-18 15:32 UTC, merged