fix busnummer error
OnroerendErfgoed/oerelia pull request #353
Opened 2023-08-09 09:58 UTC by pegahmoh

refs #352

2023-08-09 13:20 UTC, cedrikv requested changes
ik heb nog errors hier:
![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/625b5ec2-8c7e-4f10-b05b-c5f9445dbf98)

testen in vlaanderen en buiten vlaanderen. 
binnen vlaanderen mogen huisnummer/busnummer custom zijn (dus niet uit de lijst), buiten vlaanderen mogen postcode/straat/huisnummer/busnummer custom zijn. 
als er in een dropdown iets ingevuld wordt dat niet in de lijst staat, moeten de volgende velden geen lijst meer aanbieden. (dus enkel lisjt ophalen als er id is van vorige drop down)

2023-08-09 13:38 UTC, cedrikv commented
indien mogelijk ook nog zien dat als jje bvb de gemeente aanpast, straat, huisnummer & busnummer gereset worden

2023-08-10 13:49 UTC, roefem approved these changes

2023-08-11 07:03 UTC, cedrikv commented on src/autocomplete/autocomplete.ts
> +            if (suggestions && suggestions.length === 1 && this.type !== autocompleteType.Suggest) {
maak nie veel uit, maar moet die check extra check op suggestions er wel bij als we hier in de 'else ' zitten van 'if (!suggestions)...'?

2023-08-11 07:24 UTC, cedrikv reviewed
not sure if intended, maar busnummer blijft disabled bij ander land dan België
![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/71e4b3bd-52ff-4d8e-b354-3ddac62917f0)

2023-08-11 07:28 UTC, cedrikv requested changes
busnummer wordt nie mee opgeslagen bij vrij adres:
![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/1a6c79ec-19e2-4f03-b6ed-862458ece52d)

2023-08-17 06:08 UTC, pegahmoh commented
> busnummer wordt nie mee opgeslagen bij vrij adres: ![image](https://user-images.githubusercontent.com/1849458/259946504-1a6c79ec-19e2-4f03-b6ed-862458ece52d.png)

De request payload lijkt me in orde:
![Screenshot from 2023-08-17 08-04-52](https://github.com/OnroerendErfgoed/oerelia/assets/32901939/9245c505-5486-40bf-a194-03361846fa07)

In de response is busnummer null. @vancamti Dat is bij referentieadres van premieaanvragen.

2023-08-17 09:11 UTC, cedrikv requested changes
Nog kleine bug, je kan in disabled veld typen
![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/d991d34f-d10d-4418-ad79-61b63f6d7cc1)

en ook error bij ophalen straten:
![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/5772b063-253a-48d6-b472-86b903d8abf5)

2023-08-21 14:53 UTC, cedrikv requested changes
ik heb nog de error nu; niet zeker of ik op laatste versie zit
"oerelia@github:onroerenderfgoed/oerelia#bugfix/352_error_busnummer_bij_vrij_huisnummer":
  version "0.28.0"
  resolved "https://codeload.github.com/onroerenderfgoed/oerelia/tar.gz/649912c6df7a13a42a4c6c353f63b2d1c24c6857"

![image](https://github.com/OnroerendErfgoed/oerelia/assets/1849458/890665f7-3e27-4d98-ba08-3fa11d4b8067)

2023-08-23 07:27 UTC, pegahmoh commented
@cedrikv Ik heb dat opnieuw getest in premieaanvragen en ook in toelatinge_beschermd_erfgoed_aanvragen (https://github.com/OnroerendErfgoed/toelatingen_beschermd_erfgoed_aanvragen/tree/feature/epic_1008/1050_adressencomponent_gelijktrekken_met_vue_versie_update) en ik zie die errors niet meer.

2023-08-23 09:11 UTC, cedrikv approved these changes

2023-08-23 09:11 UTC, merged